CREATE TABLE IF NOT EXISTS schema_migrations (
    version text PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS companies (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    website text,
    description text,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS career_sources (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id bigint NOT NULL REFERENCES companies(id) ON DELETE CASCADE,
    career_page text NOT NULL,
    ats_label text NOT NULL,
    active boolean NOT NULL DEFAULT true,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE (company_id, career_page)
);

CREATE TABLE IF NOT EXISTS crawl_runs (
    id uuid PRIMARY KEY,
    started_at timestamptz NOT NULL DEFAULT now(),
    finished_at timestamptz,
    status text NOT NULL DEFAULT 'running' CHECK (status IN ('running', 'succeeded', 'failed')),
    discovered_count integer NOT NULL DEFAULT 0,
    inserted_count integer NOT NULL DEFAULT 0,
    updated_count integer NOT NULL DEFAULT 0,
    skipped_count integer NOT NULL DEFAULT 0,
    deleted_count integer NOT NULL DEFAULT 0,
    error text
);

-- Fingerprints are deliberately small and outlive the full job row. They stop an
-- expired role from being re-added as a new job on the next crawl.
CREATE TABLE IF NOT EXISTS job_fingerprints (
    identity_key text PRIMARY KEY,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS job_url_aliases (
    url_key text PRIMARY KEY,
    identity_key text NOT NULL REFERENCES job_fingerprints(identity_key) ON DELETE CASCADE,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS job_url_aliases_identity_idx ON job_url_aliases (identity_key);

CREATE TABLE IF NOT EXISTS jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    identity_key text NOT NULL UNIQUE REFERENCES job_fingerprints(identity_key) ON UPDATE CASCADE,
    url_key text UNIQUE,
    company_name text NOT NULL,
    title text NOT NULL,
    location text NOT NULL,
    canonical_url text,
    description text,
    employment_type text,
    department text,
    role text NOT NULL,
    level text,
    work_mode text,
    tech_stack text[] NOT NULL DEFAULT '{}',
    keywords text[] NOT NULL DEFAULT '{}',
    classification_version text NOT NULL,
    posted_at date,
    company_description text,
    remote text,
    ats_label text,
    source text,
    first_seen_at timestamptz NOT NULL DEFAULT now(),
    last_seen_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS jobs_posted_at_idx ON jobs (posted_at DESC);
CREATE INDEX IF NOT EXISTS jobs_last_seen_at_idx ON jobs (last_seen_at DESC);
CREATE INDEX IF NOT EXISTS jobs_role_idx ON jobs (role);

CREATE OR REPLACE VIEW public_jobs AS
SELECT *
FROM jobs
WHERE COALESCE(posted_at, (first_seen_at AT TIME ZONE 'Europe/Berlin')::date)
    >= ((now() AT TIME ZONE 'Europe/Berlin')::date - 30);

CREATE OR REPLACE VIEW daily_jobs AS
SELECT *
FROM public_jobs
WHERE posted_at BETWEEN ((now() AT TIME ZONE 'Europe/Berlin')::date - 1)
                    AND (now() AT TIME ZONE 'Europe/Berlin')::date;

CREATE OR REPLACE VIEW data_status AS
SELECT max(updated_at) AS updated_at, count(*)::integer AS job_count
FROM public_jobs;
