CREATE TABLE IF NOT EXISTS company_suggestions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_issue bigint NOT NULL UNIQUE,
    source_url text NOT NULL,
    name text NOT NULL,
    website text NOT NULL,
    career_page text NOT NULL,
    ats_label text,
    berlin_evidence text NOT NULL,
    status text NOT NULL DEFAULT 'submitted'
        CHECK (status IN ('submitted', 'needs_info', 'verified', 'approved', 'rejected', 'disabled')),
    submitted_at timestamptz NOT NULL,
    verified_at timestamptz,
    decided_at timestamptz,
    notes text,
    last_error text,
    updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS company_suggestion_events (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    suggestion_id bigint NOT NULL REFERENCES company_suggestions(id) ON DELETE CASCADE,
    status text NOT NULL
        CHECK (status IN ('submitted', 'needs_info', 'verified', 'approved', 'rejected', 'disabled')),
    actor text,
    detail jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS company_suggestion_events_suggestion_idx
    ON company_suggestion_events (suggestion_id, created_at);
